import { Component, signal, inject, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink, ActivatedRoute } from '@angular/router';
import { ApiService, ApiError } from '../../core/api.service';
import { AuthService } from '../../core/auth.service';

interface ApiFeature {
  id: string;
  name: string;
  endpoint: string;
  demoEndpoint: string;
  badge: string;
  description: string;
  defaultPayload: object;
  hint: string;
}

@Component({
  selector: 'app-features',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="features-page container py-12">
      <div class="page-head">
        <div class="eyebrow">LIVE INTERACTIVE DEMOS</div>
        <h1>AccessOS AI API Suite</h1>
        <p class="lede">Run real AI inferences directly in your browser against our live backend. Every result is generated by the configured AI provider — no mocked data.</p>
      </div>

      <!-- Auth Banner -->
      <div class="auth-banner" *ngIf="!isLoggedIn()">
        <span>⚡</span>
        <span>Sign in to run live inferences against the real API.</span>
        <a routerLink="/login" class="btn btn-primary btn-sm">Sign In</a>
      </div>

      <!-- Feature Tabs -->
      <div class="api-tabs mb-8">
        <button
          *ngFor="let api of apis"
          class="tab-btn"
          [class.active]="activeApi().id === api.id"
          (click)="selectApi(api)"
        >
          {{ api.name }}
        </button>
      </div>

      <!-- Active Feature Card -->
      <div class="card demo-card">
        <div class="demo-head">
          <div>
            <span class="status-chip live">LIVE API</span>
            <h2 class="mt-2">{{ activeApi().name }}</h2>
            <p class="muted font-mono text-sm">{{ activeApi().endpoint }}</p>
          </div>
          <a routerLink="/docs" class="btn btn-ghost">View API Docs →</a>
        </div>

        <p class="mb-2 text-sm">{{ activeApi().description }}</p>
        <p class="hint-text mb-6">{{ activeApi().hint }}</p>

        <div class="grid-2">
          <!-- Request Editor -->
          <div class="pane">
            <div class="pane-head">
              <span class="mono">Request Payload</span>
              <span class="mono muted">JSON</span>
            </div>
            <textarea
              rows="10"
              [(ngModel)]="payloadText"
              class="font-mono text-xs"
              [class.invalid]="jsonError()"
              (input)="onPayloadInput()"
            ></textarea>
            <div class="json-error" *ngIf="jsonError()">⚠ Invalid JSON</div>
            <button
              class="btn btn-primary mt-4 w-full"
              (click)="runInference()"
              [disabled]="running() || !isLoggedIn() || !!jsonError()"
            >
              <span *ngIf="!running()">{{ isLoggedIn() ? 'Run Real Inference' : 'Sign in to Run' }}</span>
              <span *ngIf="running()" class="flex-center gap-2">
                <span class="spinner"></span> Running…
              </span>
            </button>
          </div>

          <!-- Response Viewer -->
          <div class="pane">
            <div class="pane-head">
              <div class="flex-center gap-2">
                <span class="mono">Response</span>
                <span class="status-badge ok" *ngIf="lastStatus() === 200">200 OK</span>
                <span class="status-badge err" *ngIf="lastStatus() && lastStatus() !== 200">{{ lastStatus() }}</span>
                <span class="latency-label" *ngIf="latencyMs() !== null">{{ latencyMs() }}ms</span>
              </div>
              <button class="copy-btn" (click)="copyResponse()" *ngIf="responseText()">
                {{ copied() ? '✓ Copied' : 'Copy' }}
              </button>
            </div>
            <div class="response-box font-mono text-xs">
              <pre *ngIf="responseText()"><code>{{ responseText() }}</code></pre>
              <div class="empty-hint" *ngIf="!responseText() && !running()">
                <div class="empty-icon">◎</div>
                <span class="muted">Click "Run Real Inference" to execute the payload against the live AI backend.</span>
              </div>
              <div class="empty-hint" *ngIf="running()">
                <span class="spinner lg"></span>
                <span class="muted mt-2">Calling {{ activeApi().name }}…</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .auth-banner {
      display: flex; align-items: center; gap: 12px; background: rgba(245, 158, 11, 0.08);
      border: 1px solid rgba(245, 158, 11, 0.3); border-radius: var(--radius-md);
      padding: 12px 18px; margin-bottom: 24px; font-size: 14px; color: #fbbf24;
    }
    .auth-banner .btn { margin-left: auto; }
    .btn-sm { padding: 6px 14px; font-size: 12px; }

    .api-tabs { display: flex; gap: 8px; flex-wrap: wrap; border-bottom: 1px solid var(--line); padding-bottom: 12px; }
    .tab-btn {
      background: transparent; border: 1px solid var(--line);
      color: var(--ink-soft); padding: 8px 16px; border-radius: var(--radius-sm);
      font-family: var(--font-sans); font-size: 14px; font-weight: 500; cursor: pointer;
      transition: all var(--duration-fast) var(--ease);
    }
    .tab-btn:hover { color: #fff; background: rgba(255,255,255,0.04); }
    .tab-btn.active { color: #fff; background: var(--accent-soft); border-color: var(--accent); }

    .demo-head { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; }
    .hint-text { font-size: 12px; color: var(--ink-muted); font-style: italic; }

    .pane { display: flex; flex-direction: column; }
    .pane-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; font-size: 12px; color: var(--ink-muted); }

    textarea { border-color: var(--line); transition: border-color 0.2s; }
    textarea.invalid { border-color: #ef4444 !important; }
    .json-error { color: #ef4444; font-size: 11px; margin-top: 4px; }

    .response-box {
      background: var(--bg-deep); border: 1px solid var(--line);
      border-radius: var(--radius-md); padding: 16px; height: 250px; overflow-y: auto; flex: 1;
    }
    .empty-hint { height: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; gap: 8px; }
    .empty-icon { font-size: 28px; opacity: 0.3; }

    .copy-btn { background: transparent; border: 1px solid var(--line); color: var(--ink); padding: 2px 8px; border-radius: var(--radius-sm); cursor: pointer; font-size: 11px; }
    .copy-btn:hover { border-color: var(--accent); color: var(--accent); }

    .status-badge { font-size: 10px; font-weight: 600; padding: 2px 6px; border-radius: 4px; }
    .status-badge.ok { background: rgba(34,197,94,0.15); color: #4ade80; }
    .status-badge.err { background: rgba(239,68,68,0.15); color: #f87171; }
    .latency-label { font-size: 11px; color: var(--accent); font-weight: 600; }

    .flex-center { display: flex; align-items: center; }
    .gap-2 { gap: 8px; }
    .mt-2 { margin-top: 8px; }

    .spinner { display: inline-block; width: 14px; height: 14px; border: 2px solid rgba(255,255,255,0.2); border-top-color: #fff; border-radius: 50%; animation: spin 0.7s linear infinite; }
    .spinner.lg { width: 28px; height: 28px; border-width: 3px; }
    @keyframes spin { to { transform: rotate(360deg); } }
  `],
})
export class FeaturesComponent implements OnInit {
  private api = inject(ApiService);
  private authService = inject(AuthService);
  private route = inject(ActivatedRoute);

  isLoggedIn = computed(() => this.authService.isLoggedIn());

  apis: ApiFeature[] = [
    {
      id: 'ocr',
      name: 'OCR',
      endpoint: 'POST /v1/ocr',
      demoEndpoint: '/v1/demo/ocr',
      badge: 'Tesseract.js',
      description: 'Extract text from any image — invoices, screenshots, signage, documents. Powered by Tesseract running server-side with no external API key.',
      defaultPayload: { image_url: 'https://c8.alamy.com/comp/B4XN1G/street-scenery-new-delhi-india-B4XN1G.jpg' },
      hint: 'Try any public image URL containing visible text. Paste a data: URI for private images.',
    },
    {
      id: 'vision',
      name: 'Vision',
      endpoint: 'POST /v1/vision',
      demoEndpoint: '/v1/demo/vision',
      badge: 'OpenAI / Gemini',
      description: 'Generate detailed scene descriptions and alt text for images. Designed for screen-reader accessibility output.',
      defaultPayload: { image_url: 'https://c8.alamy.com/comp/B4XN1G/street-scenery-new-delhi-india-B4XN1G.jpg', simplified: false },
      hint: 'Set "simplified": true for Grade-5 reading level output.',
    },
    {
      id: 'simplify',
      name: 'Text Simplify',
      endpoint: 'POST /v1/simplify',
      demoEndpoint: '/v1/demo/simplify',
      badge: 'OpenAI / Gemini',
      description: 'Convert dense technical or academic text to plain language suitable for users with cognitive disabilities.',
      defaultPayload: { text: 'The mitochondria is the organelle responsible for ATP synthesis through oxidative phosphorylation in eukaryotic cells.' },
      hint: 'Paste any text. The AI will simplify it to approximately Grade 5 reading level.',
    },
    {
      id: 'sign',
      name: 'Sign Language Gloss',
      endpoint: 'POST /v1/sign-language',
      demoEndpoint: '/v1/demo/sign-language',
      badge: 'AI Gloss',
      description: 'Convert English sentences into ASL gloss notation with correct topic-comment grammar structure.',
      defaultPayload: { text: 'Where is the nearest train station?' },
      hint: 'The AI reorders words into proper ASL gloss order and identifies the grammar structure.',
    },
    {
      id: 'accessibility',
      name: 'Accessibility Orchestrator',
      endpoint: 'POST /v1/accessibility',
      demoEndpoint: '/v1/demo/accessibility',
      badge: 'Multi-Modal',
      description: 'Full pipeline: OCR + scene understanding + text simplification + sign gloss. Runs all relevant AI capabilities in parallel.',
      defaultPayload: { text: 'Please take your medication at 8 AM before breakfast.', reading_level: 'simplified' },
      hint: 'Provide image_url, text, or both. Set reading_level to "simplified" for plain-language output.',
    },
  ];

  activeApi = signal<ApiFeature>(this.apis[0]);
  payloadText = JSON.stringify(this.apis[0].defaultPayload, null, 2);
  responseText = signal<string | null>(null);
  running = signal(false);
  lastStatus = signal<number | null>(null);
  latencyMs = signal<number | null>(null);
  copied = signal(false);
  jsonError = signal<string | null>(null);

  ngOnInit() {
    this.route.queryParams.subscribe((params: Record<string, string>) => {
      const featKey = params['feature'];
      if (featKey) {
        this.applyFeatureSelection(featKey);
      }
    });

    this.route.fragment.subscribe((frag: string | null) => {
      if (frag) {
        this.applyFeatureSelection(frag);
      }
    });
  }

  private applyFeatureSelection(key: string) {
    const k = key.toLowerCase();
    let target = this.apis.find((a) => a.id === k);
    if (!target) {
      if (k.includes('eye') || k.includes('vision')) target = this.apis.find((a) => a.id === 'vision');
      else if (k.includes('hear') || k.includes('sign')) target = this.apis.find((a) => a.id === 'sign');
      else if (k.includes('hand') || k.includes('motor') || k.includes('simplify')) target = this.apis.find((a) => a.id === 'simplify');
      else if (k.includes('nav') || k.includes('access')) target = this.apis.find((a) => a.id === 'accessibility');
      else if (k.includes('ocr')) target = this.apis.find((a) => a.id === 'ocr');
    }
    if (target) {
      this.selectApi(target);
    }
  }

  selectApi(api: ApiFeature) {
    this.activeApi.set(api);
    this.payloadText = JSON.stringify(api.defaultPayload, null, 2);
    this.responseText.set(null);
    this.lastStatus.set(null);
    this.latencyMs.set(null);
    this.jsonError.set(null);
  }

  onPayloadInput() {
    try {
      JSON.parse(this.payloadText);
      this.jsonError.set(null);
    } catch {
      this.jsonError.set('Invalid JSON');
    }
  }

  runInference() {
    let payload: unknown;
    try {
      payload = JSON.parse(this.payloadText);
    } catch {
      this.jsonError.set('Fix JSON before running');
      return;
    }

    this.running.set(true);
    this.responseText.set(null);
    const start = performance.now();

    this.api.post<unknown>(this.activeApi().demoEndpoint, payload).subscribe({
      next: (res) => {
        this.latencyMs.set(Math.round(performance.now() - start));
        this.lastStatus.set(200);
        this.responseText.set(JSON.stringify(res, null, 2));
        this.running.set(false);
      },
      error: (err: ApiError) => {
        this.latencyMs.set(Math.round(performance.now() - start));
        this.lastStatus.set(err.status || 500);
        this.responseText.set(JSON.stringify({ error: err.code, detail: err.detail }, null, 2));
        this.running.set(false);
      },
    });
  }

  copyResponse() {
    const text = this.responseText();
    if (text) {
      navigator.clipboard.writeText(text);
      this.copied.set(true);
      setTimeout(() => this.copied.set(false), 2000);
    }
  }
}
